language: node_js
node_js:
  - "6"
cache:
  timeout: 500
  directories:
    - node_modules
script:
    - npm run build
notifications:
  email: false
deploy:
    - provider: script
      skip_cleanup: true
      script: node ftpdeploy.js --user ${BETA_FTP_USER} --password ${BETA_FTP_PWD} --use_strict
      on:
        tags: true
        all_branches: true
        condition: "$TRAVIS_TAG =~ .*beta.*$"
    - provider: script
      skip_cleanup: true
      script: node ftpdeploy.js --user ${DEMO_FTP_USER} --password ${DEMO_FTP_PWD} --use_strict
      on:
        tags: true
        all_branches: true
        condition: "! $TRAVIS_TAG =~ .*beta.*$"
after_deploy:
  - node slack.js --slack ${SLACK} --tag ${TRAVIS_TAG}